version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cargo build
      - run: cd examples && ./test.sh
      - run: |
          git clean -dfx
          cargo build --features cmake
